### PR TITLE
palindrom

### PR DESCRIPTION
**Pull request by Paras-Mayur8055**
i hope you will accept my request 
thank you

### CODE REVIEW

**Comment by Nikita0331** [comment]
Your code is not correct

**Comment by Paras-Mayur8055** [comment]
> Your code is not correct 
wait let me check give me a min

**Comment by Paras-Mayur8055** [comment]
> Your code is not correct

sorry for that mistake i don't know why that happened in vscode its showing correct 

i have updated it here you can check 
thank you for pointing out this

**Comment by Nikita0331** [comment]
it's ok not it's correct

**Comment by Paras-Mayur8055** [comment]
> it's ok not it's correct

are you on linkedin?
www.linkedin.com/in/parasmayur
lets connect

**Comment by Nikita0331** [comment]
yeas link in my readme file

**Comment by Paras-Mayur8055** [comment]
> yeas link in my readme file

ok let me see

**Comment by Nikita0331** [comment]
follow me on github for some amazing projects and competitive codes

**Comment by Paras-Mayur8055** [comment]
> follow me on github for some amazing projects and competitive codes

sure done on both you can check

**Pull request merged**
